<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "eventfinder"
 *
 * Auto generated by Extension Builder 2017-10-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Glibi',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Corinne & Christian Futterlieb',
    'author_email' => '',
    'state' => 'alpha',
    'clearCacheOnLoad' => 1,
    'version' => '0.1.0-dev',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
